id: AF45E4ADF
title: 'Sweet Song of Vajra Immortality: A Prayer for Long Life'
type: translation
pechas:
- I8CFB2426
- IFB23A9BD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:38.077940
  last_modified_at: 2023-01-04 11:37:38.077945
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8CFB2426/811A: 0393
  IFB23A9BD/40BA: 0393
